spring.datasource.url=jdbc:postgresql://localhost:5432/confeitaria
# link para o bd
spring.datasource.username=postgres
# usuario do bd
spring.datasource.password=admin
#senha do bd
spring.datasource.driver-class-name=org.postgresql.Driver
#driver do pG no SpringBoot

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
logging.level.org.springframework.security=DEBUG

spring:
  web:
    cors:
      enabled: true
      allowed-origins: http://127.0.0.1:5500
      allowed-methods: GET, POST, PUT, DELETE  